spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    open-in-view: false

network:
  user-auth: ${USER_AUTH_HOSTNAME}
  store: ${STORE_HOSTNAME}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}

---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    properties:
      hibernate:
        show_sql: true
    generate-ddl: true

---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    properties:
      hibernate:
        show_sql: false
    generate-ddl: false
